### ISSUE TITLE
Cave Schematic

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/CaveBlock#14]
#### Description
The cave schematic is pasted as if it was -a. As in it does not replace the exsisting stone blocks with air when pasted 

####  Steps to reproduce the behavior:
Use the schem i made then try to generate a cave 

#### Expected behavior
For the Schem to be pasted and the air blocks to be set and the stone that is pre exsisting to be removed

#### Screenshots or video
![image](https://user-images.githubusercontent.com/41904721/52655777-1ef4f980-2f49-11e9-9892-90ca34e9b3da.png)

#### Server Information:
![image](https://user-images.githubusercontent.com/41904721/52655814-346a2380-2f49-11e9-80a7-d36a28fe56dc.png)

####  Additional context
Made the schem like in other gamemodes 
followed this https://www.youtube.com/watch?v=hFkP7hit3i4&t=41s

and no i did not copy -a 

[schem.zip](https://github.com/BentoBoxWorld/CaveBlock/files/2856937/schem.zip)

**Comment by robert-beckley** [comment]
[WE SCHEM.zip](https://github.com/BentoBoxWorld/CaveBlock/files/2856967/WE.SCHEM.zip)
Here is the schem in WorldEdit format so you can paste and see what it is meant to be

**Comment by robert-beckley** [comment]
@BONNe the first timeout 
13.02 05:10:47 [Server] INFO robert_beckley issued server command: /cba schem save island
13.02 05:10:49 [Server] INFO robert_beckley issued server command: /cba schem save island
13.02 05:11:27 [Server] WARN Task #2227 for BentoBox v1.3.0-SNAPSHOT generated an exception
13.02 05:11:27 [Server] INFO java.lang.OutOfMemoryError: Java heap space
13.02 05:11:27 [Server] INFO at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_191]
13.02 05:11:27 [Server] INFO at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[?:1.8.0_191]
13.02 05:11:27 [Server] INFO at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[?:1.8.0_191]
13.02 05:11:27 [Server] INFO at java.lang.StringBuffer.append(StringBuffer.java:270) ~[?:1.8.0_191]
13.02 05:11:27 [Server] INFO at java.io.StringWriter.write(StringWriter.java:112) ~[?:1.8.0_191]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.writePlain(Emitter.java:1474) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.processScalar(Emitter.java:799) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.expectScalar(Emitter.java:424) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:393) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:644) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:218) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:197) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:195) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:195) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:111) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at world.bentobox.bentobox.schems.Clipboard.save(Clipboard.java:663) ~[?:?]
13.02 05:11:27 [Server] INFO at world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand.lambda$execute$0(AdminSchemSaveCommand.java:38) ~[?:?]
13.02 05:11:27 [Server] INFO at world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand$$Lambda$2750/1087552422.run(Unknown Source) ~[?:?]
13.02 05:11:27 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:11:27 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]

**Comment by robert-beckley** [comment]
the full crash 
13.02 05:14:48 [Server] INFO robert_beckley issued server command: /cba schem copy air
13.02 05:15:28 [Server] INFO robert_beckley issued server command: /cba schem save island
13.02 05:15:30 [Server] INFO robert_beckley issued server command: /cba schem save island
13.02 05:16:30 [Server] ERROR ------------------------------
13.02 05:16:30 [Server] ERROR The server has stopped responding! This is (probably) not a Spigot bug.
13.02 05:16:30 [Server] ERROR If you see a plugin in the Server thread dump below, then please report it to that author
13.02 05:16:30 [Server] ERROR *Especially* if it looks like HTTP or MySQL operations are occurring
13.02 05:16:30 [Server] ERROR If you see a world save or edit, then it means you did far more than your server can handle at once
13.02 05:16:30 [Server] ERROR If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
13.02 05:16:30 [Server] ERROR If you are unsure or still think this is a Spigot bug, please report to https://www.spigotmc.org/
13.02 05:16:30 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
13.02 05:16:30 [Server] ERROR Spigot version: git-Spigot-a1f2566-97b0057 (MC: 1.13.2)
13.02 05:16:30 [Server] ERROR ------------------------------
13.02 05:16:30 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
13.02 05:16:30 [Server] ERROR ------------------------------
13.02 05:16:30 [Server] ERROR Current Thread: Server thread
13.02 05:16:30 [Server] ERROR PID: 18 | Suspended: false | Native: false | State: RUNNABLE
13.02 05:16:30 [Server] ERROR Stack:
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:156)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:194)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:195)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:111)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
13.02 05:16:30 [Server] ERROR org.yaml.snakeyaml.Yaml.dump(Yaml.java:245)
13.02 05:16:30 [Server] ERROR org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
13.02 05:16:30 [Server] ERROR org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66)
13.02 05:16:30 [Server] ERROR world.bentobox.bentobox.schems.Clipboard.save(Clipboard.java:663)
13.02 05:16:30 [Server] ERROR world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand.lambda$execute$0(AdminSchemSaveCommand.java:38)
13.02 05:16:30 [Server] ERROR world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand$$Lambda$2750/1087552422.run(Unknown Source)
13.02 05:16:30 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
13.02 05:16:30 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
13.02 05:16:30 [Server] ERROR net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)

13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:393) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingKey.expect(Emitter.java:630) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:218) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:170) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:194) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:195) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:111) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at world.bentobox.bentobox.schems.Clipboard.save(Clipboard.java:663) ~[?:?]
13.02 05:16:39 [Server] INFO at world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand.lambda$execute$0(AdminSchemSaveCommand.java:38) ~[?:?]
13.02 05:16:39 [Server] INFO at world.bentobox.bentobox.api.commands.admin.schem.AdminSchemSaveCommand$$Lambda$2750/1087552422.run(Unknown Source) ~[?:?]
13.02 05:16:39 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:39 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot_1.13.2.jar:git-Spigot-a1f2566-97b0057]
13.02 05:16:40 [Multicraft] Skipped 539 lines due to rate limit (30/s)

**Comment by tastybento** [comment]
I don’t know about the crash logs but did you copy air when your made the schem? You need to do /cba schem copy air to copy air.

**Comment by tastybento** [comment]
The crash log is an out of memory error when saving the schem. Hmm. Maybe i’m out of the loop in a conversation you are having with Bonne because it doesn’t seem related to the bug report.

**Comment by robert-beckley** [comment]
Issue has been resolved on discord. An extra step in the guide should be
added
