### ISSUE TITLE
WelcomeWarpSign-CaveBlock

### ISSUE THREAD

**Issue by Oskar140316** [BentoBoxWorld/CaveBlock#16]
addtion to welcome warp sign does not work

**Comment by OverBrave** [comment]
delete config of "addon-welcomewarpsigns" and try again.

**Comment by Oskar140316** [comment]
and where is this configuration?

**Comment by tastybento** [comment]
I agree with @OverBrave - you probably have an old config.yml for WelcomeWarps. It changed a while ago to support CaveBlock and other game modes. Delete the config.yml file:

`plugins -> BentoBox -> addons -> WelcomeWarps -> config.yml`

You can check if Welcome Warps has loaded by doing /bbox version:

```
[08:52:36 INFO]: 
  ____             _        ____
 |  _ \           | |      |  _ \             by tastybento and Poslovitch
 | |_) | ___ _ __ | |_ ___ | |_) | _____  __  2017 - 2019
 |  _ < / _ \ '_ \| __/ _ \|  _ < / _ \ \/ /
 | |_) |  __/ | | | || (_) | |_) | (_) >  <   v1.4.0-SNAPSHOT
 |____/ \___|_| |_|\__\___/|____/ \___/_/\_\  Loaded in 12406ms.

[08:52:37 INFO]: [PlaceholderAPI] 125 placeholder expansions are available on the cloud.
>bbox version
[08:52:44 INFO]: Running SPIGOT 1.13.2.
[08:52:44 INFO]: BentoBox version: 1.4.0-SNAPSHOT
[08:52:44 INFO]: Loaded Game Worlds:
[08:52:44 INFO]: AcidIsland_world (AcidIsland)
[08:52:44 INFO]: CaveBlock-world (CaveBlock)
[08:52:44 INFO]: Loaded Addons:
[08:52:44 INFO]: AcidIsland 1.4.0-SNAPSHOT
[08:52:44 INFO]: CaveBlock 1.3.0
[08:52:44 INFO]: Level 1.3.0
[08:52:44 INFO]: WelcomeWarps 1.2.1-SNAPSHOT
```

Next time, it'd be good for you to provide the information in the Bug Report button template so we know what version of addons etc. you have.

**Comment by Oskar140316** [comment]
I think I have an old plug for the welcome sign (0.1.0). Where do I get the latest plugins from?

**Comment by tastybento** [comment]
Yes the releases are dragging and need to be brought up to date. Latest builds are here
https://ci.codemc.org/

**Comment by Oskar140316** [comment]
thanks to
