### ISSUE TITLE
CaveBlock Placeholders

### ISSUE THREAD

**Issue by Oskar140316** [BentoBoxWorld/CaveBlock#18]
How do I use the placeholders of this plugin? (PlaceholderApi)

**Comment by Poslovitch** [comment]
Make sure PlaceholderAPI is installed. Then : https://github.com/BentoBoxWorld/CaveBlock/wiki/Placeholders

**Comment by Oskar140316** [comment]
is installed but still not working and you can download these placeholders?

**Comment by Poslovitch** [comment]
These placeholders were added in BentoBox 1.4.0. So you need to make sure you're using that version.

**Comment by BONNe** [comment]
So for some plugins that use placeholder api it could be necessary to add `placeholderapi_` before it or for EssentialsChat you need https://www.spigotmc.org/resources/chatinjector.38327/.

**Comment by Oskar140316** [comment]
a where to download caveblock 1.4.0? because on ci.codemc.org I haven't seen it

**Comment by Oskar140316** [comment]
is the command to download placeholders? when he writes the command /cave help, he writes that this command is unknown
