### ISSUE TITLE
CaveBlock not working on minecraft 1.14.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/CaveBlock#22]
#### Description
CaveBlock not working on minecraft 1.14.
The console is frozen. Unable to login to server.
The command is not written.

#### Screenshots or video
![image](https://user-images.githubusercontent.com/47111280/57650612-dd213100-75d3-11e9-87ad-c3544cf9846f.png)
![image](https://user-images.githubusercontent.com/47111280/57650628-e7dbc600-75d3-11e9-93f8-7221502bd64b.png)
![image](https://user-images.githubusercontent.com/47111280/57650633-ea3e2000-75d3-11e9-8f8b-d5c462c2b736.png)

#### Server Information:
 - Java Version: Java 8
 - BentoBox version: Latest Dev buil (BentoBox 1.5.0 Snapshot)
 - Addons installed? Only Caveblock

**Comment by tastybento** [comment]
1.14 isn't supported yet. There's a dev branch of 1.14 BentoBox that you'd need but I'm pretty sure CaveBlock isn't supported yet. Once we get 1.5.0 out we'll work on 1.14 support. Or 1.14.1 support because that's when some serious bugs will be fixed.

**Comment by OverBrave** [comment]
Will Bento Box 1.5 support Minecraft 1.14.1? Because Paper 1.14.1 its release!

**Comment by Poslovitch** [comment]
No, it won't. Full 1.14+ support is planned for 1.6.0.

**Comment by OverBrave** [comment]
That's very bad news. I hope you develop fast. Because I'm gonna have to wait too long.

**Comment by tastybento** [comment]
We’ll do it when we can. Thanks for your support.

**Comment by BONNe** [comment]
I will keep it open, as I think it should work in 1.14 version
