### ISSUE TITLE
Is there anything can help for this???

### ISSUE THREAD

**Issue by Krixiz** [BentoBoxWorld/CaveBlock#24]
Server freeze sometime even more when they are creating new island
There anything can help?? please
![image](https://user-images.githubusercontent.com/50483551/57873078-80be4b80-7837-11e9-95e5-3945c5421b74.png)

**Comment by BONNe** [comment]
Create smaller schem.

**Comment by Krixiz** [comment]
> Create smaller schem.

How can i create smaller schem. help me please ?
