### ISSUE TITLE
Schematic not working

### ISSUE THREAD

**Issue by BlackTen** [BentoBoxWorld/CaveBlock#26]
Hi, I'm create a file island.schem but he not working. 
Displays to me "That warp is not safe now".

My steps:
1. /cba schem pos1
2. /cba schem pos2
3. /cba schem origin
4. /cba schem copy
5. /cba schem save island

Can you help me, please?

**Comment by BONNe** [comment]
BentoBox v output?

**Comment by BlackTen** [comment]
What?
