### ISSUE TITLE
CaveBlock issues.

### ISSUE THREAD

**Issue by EnderBro123** [BentoBoxWorld/CaveBlock#30]
#### Description
CaveBlock is bugging out.

####  Steps to reproduce the behavior:
1. Create a Cave via /cb.
2. Upon entering your Cave, wait 5-10 seconds, and poof. Your face is covered with smooth stone.

#### Expected behavior
The plugin not bugging out.

#### Screenshots or video
Before:
![2019-06-28_15 52 30](https://user-images.githubusercontent.com/51277766/60375296-773f0c00-99bd-11e9-89b8-b8893d4c8b1e.png)

After:
![2019-06-28_15 52 59](https://user-images.githubusercontent.com/51277766/60375304-83c36480-99bd-11e9-9db2-1bb210bcd58a.png)

#### Server Information:
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [] None.
 - OS: [e.g. iOS] Using BiscuitHosting. No idea.
 - Java Version: [e.g. Java 8] Using BiscuitHosting. No idea.
 - BentoBox version: [e.g. 1.7.2.21] 
![2019-06-28_15 56 47](https://user-images.githubusercontent.com/51277766/60375272-5971a700-99bd-11e9-93a2-eaa965ce8a4b.png)

 - Addons installed? [Do '/bentobox version' and copy/paste from the console] Error shows up upon usage. Can't.
 - Other plugins? [Do '/plugins' and copy/paste from the console]

![2019-06-28_15 54 28](https://user-images.githubusercontent.com/51277766/60375257-3ba44200-99bd-11e9-8d77-95df3c5cb766.png)

**Comment by EnderBro123** [comment]
Edit: I might update BB right now, I ended up not noticing this till now.

**Comment by tastybento** [comment]
Do you have clean super flat set to true? That'll cause this problem.

Stop the server, look at the CaveBlock config.yml file and change CLEAN_SUPER_FLAT: true to CLEAN_SUPER_FLAT: false. It's around line 197.

**Comment by EnderBro123** [comment]
> Do you have clean super flat set to true? That'll cause this problem.
> 
> Stop the server, look at the CaveBlock config.yml file and change CLEAN_SUPER_FLAT: true to CLEAN_SUPER_FLAT: false. It's around line 197.

Tried setting it to False and still happens.
