### ISSUE TITLE
Reprint request

### ISSUE THREAD

**Issue by LittleHed** [BentoBoxWorld/CaveBlock#37]
Hello,I think this plugin is very good.May I reprint it to the one of the china website: [mcbbs.net](url) ?
I want more people know about this plugin. thx

**Comment by tastybento** [comment]
Yes. But remember to explain that BentoBox is the plugin and CaveBlock is an addon to BentoBox.

**Comment by LittleHed** [comment]
thx

**Comment by LittleHed** [comment]
搬运证明，我是小呵哦
It just a prove of reprint to give the Audit of the web of mcbbs.net a look
