### ISSUE TITLE
Problem with coop and trust

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/CaveBlock#38]
The command /cv team coop and trust does not work because of defult are set of permissions that do not give access to users in coop or trust to break blocks etc.

I saw in the config this section where you can choose via values to whom to allow certain things. There is a comment that says:
"# Ranks are: Visitor = 0, Member = 900, Owner = 1000"

Well okay .. but for the users in coop and in trusts which values should be used? To give them access too

https://hastebin.com/amonupebem.coffeescript

**Comment by Poslovitch** [comment]
Comments in the config need to be updated. I'll do that.

**Comment by Poslovitch** [comment]
I just updated the comments.

Here is the list of all the ranks values:

```
VISITOR   = 0
COOP      = 200
TRUSTED   = 400
MEMBER    = 500
SUB-OWNER = 900
OWNER     = 1000
```

**Comment by Manu5656** [comment]
Fine thanks a lot!

**Comment by Manu5656** [comment]
Will the previously created caves remain with the old settings or will they update with new ones?

**Comment by Poslovitch** [comment]
They will keep their old settings. You can however reset these using the `/cba resetflags` command.

**Comment by Manu5656** [comment]
Ok, thank you
