### ISSUE TITLE
Alternative nether and end gate.

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/CaveBlock#4]
#### Describe the solution you'd like
It would be awesome, if users are teleport to nether, if they dig down, for example, reach level 0. 
And if they dig up, and reach world high limit, they are teleport to the end.

**Comment by Poslovitch** [comment]
That's basically what Stoneblock does, if I'm not misunderstood. However, I think that the End is reached by digging down the Nether

**Comment by BONNe** [comment]
Implemented:

- from over world by digging down users will be teleported to the nether.
- from nether by digging down users will be teleported to the end.
- from the end by digging down users will be teleported to the over world.

It will work only if world floor is disabled.

**Comment by robert-beckley** [comment]
This does not seem to be working 

![image](https://user-images.githubusercontent.com/41904721/52657129-09cd9a00-2f4c-11e9-8f1f-1eb3a3bc792d.png)

[Void Drop.zip](https://github.com/BentoBoxWorld/CaveBlock/files/2857034/Void.Drop.zip)
https://youtu.be/Wyw0VP-ZgZ0
