### ISSUE TITLE
How to invite players to join a team?

### ISSUE THREAD

**Issue by iLeak** [BentoBoxWorld/CaveBlock#42]
Hello!
I did not see this instruction in help.
But there are teams.
Can you tell me how to invite players and remove the players?
Thank you!

**Comment by BONNe** [comment]
`/cave team invite [player]`

**Comment by iLeak** [comment]
> `/cave team invite [player]`

thank you! how to remove players?
I don't understand these.Because i from other countries.

**Comment by BONNe** [comment]
`/cave team kick`

**Comment by iLeak** [comment]
> `/cave team kick`

Thank you very much. I like this plugin very much. My players also like it.
Looking forward to creating new and interesting gameplay.
