### ISSUE TITLE
Is this plugins any permissions?

### ISSUE THREAD

**Issue by LittleHed** [BentoBoxWorld/CaveBlock#46]
Umm,sorry i don't know any permissions of it

**Comment by Poslovitch** [comment]
https://bentobox-world.readthedocs.io/en/latest/gamemodes/CaveBlock/Permissions/

**Comment by LittleHed** [comment]
Sorry,does it have other version for chinese?

**Comment by Poslovitch** [comment]
No, sorry. None of our contributors/developers speak Chinese.

**Comment by LittleHed** [comment]
OK,I can try to translate it to chinese
