### ISSUE TITLE
Beacon Digger

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/CaveBlock#5]
#### Is your feature request related to a problem? Please describe.
Currently, if world ceiling is made of bedrock, users cannot use beacon.

#### Describe the solution you'd like
If user places beacon, then bedrock on the top are broken, but if he breaks it, it is replaced.

#### Describe alternatives you've considered
Create block, that will dig everything till the top and replace it with air.

**Comment by tastybento** [comment]
By the way, glass works too. You could replace everything with air and maybe the bedrock with some indestructible glass. :-)

**Comment by BONNe** [comment]
Partially implemented. 
I decide not to implement ability to dig all blocks from beacon till the top, as it will be overpowered and easily abusive.
My implementation will work only if roof is made of bedrock, and it will replace bedrock with black glass. 
It should be understandable and it will be replaced with bedrock as soon as beacon is removed.
