### ISSUE TITLE
1.13x加载不了此插件

### ISSUE THREAD

**Issue by mc2514** [BentoBoxWorld/CaveBlock#80]
### Is your feature request related to a problem?

1

### Describe the solution you'd like.

1

### Describe alternatives you've considered.

1

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
For Minecraft 1.13 you need to use https://github.com/BentoBoxWorld/CaveBlock/releases/tag/1.11.0

Also, be aware, you need [BentoBox 1.10.0](https://github.com/BentoBoxWorld/BentoBox/releases/tag/1.10.0).

BentoBox is mostly single version specific. Unfortunately, we do not have backward support.
