### ISSUE TITLE
caveblock-world/bentobox

### ISSUE THREAD

**Issue by BigAppleClass** [BentoBoxWorld/CaveBlock#97]
### Expected behavior

![image](https://github.com/user-attachments/assets/c76048d2-7acc-4f89-a2c1-adaa62dcd599)

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/1d0a864a-13ab-472e-89e2-23c841af4dd4)

### Steps/models to reproduce

![image](https://github.com/user-attachments/assets/9b6c84e0-fb16-4bcf-a5d9-470db72f8296)

### BentoBox version

![image](https://github.com/user-attachments/assets/784cb48f-81ac-45a4-9abf-558f6cbd6176)

### Plugin list

![image](https://github.com/user-attachments/assets/0b1ab05d-fbef-4342-a6f8-c3285b11007e)

### Other

![image](https://github.com/user-attachments/assets/fb782f97-1ff5-4a74-a88b-68dda3892eee)

**Comment by BigAppleClass** [comment]
In 1.21.4 there will be two worlds, I don't know what's going on, sorry I won't send lss either

**Comment by tastybento** [comment]
Yes, there is a seed world that is used to regenerate CaveBlock worlds. It is generated the same as the main world but kept perfect and then when the user deletes their island, the chunks are copied over. So this is expected.
